### ISSUE TITLE
Copyright issues on publicizing kato data?

### ISSUE THREAD

**Issue by theideasmith** [openworm/neuronal-analysis#11]
@lukeczapla  and I obtained the data from Manuel Zimmer. Going forward, I'm wondering if we need to check with them if publicizing the data is OK. We didn't get any sharing guidelines in the email from them, but I just want to be safe here. 

Thoughts anyone?

**Comment by slarson** [comment]
Ah, yeah.  I didn't realize that.  You should ask them.  Default is
copyright goes to the original author.  Best is if you can get them to
agree to a data sharing license.  Email sent to you with the agreement
should be sufficient.

I'd correspond with the following:
http://opendatacommons.org/guide/

If they are hesitant, probably better to take the data sets down (which
would be unfortunate, but more correct).

**Comment by theideasmith** [comment]
If we do need to take them down, maybe we can harness @benjijack's RNNs generate surrogate datasets; would these be under the potential copyright as well because they are a derivative of the original data?

**Comment by lukeczapla** [comment]
hi Akiva, the technical details of copyright are not a big factor to worry about for this non-commercial project that we are doing for the sake of science; if they do have an issue (very improbable) then of course we should take it down.  

Let me follow up with them, the polite thing to do is follow up with any major findings that have happened as a result of getting the data.  Since we have developed an open-source tool to analyze their data within the OpenWorm simulation project, that sounds like a good reason to send them a short note.

**Comment by slarson** [comment]
Closing because the question was answered
